#include <Box2D/Box2D.h>
#include <Box2D/Collision/b2BroadPhase.cpp>
#include <Box2D/Collision/b2DynamicTree.cpp>
#include <Box2D/Common/b2BlockAllocator.cpp>
#include <Box2D/Common/b2Math.cpp>
#include <Box2D/Common/b2StackAllocator.cpp>
#include <Box2D/Common/b2Settings.cpp>
#include <Box2D/Common/b2TrackedBlock.cpp>
#include <Box2D/Dynamics/b2Body.cpp>
#include <Box2D/Dynamics/b2ContactManager.cpp>
#include <Box2D/Dynamics/b2Fixture.cpp>
#include <Box2D/Dynamics/b2World.cpp>
#include <Box2D/Dynamics/b2WorldCallbacks.cpp>
#include <Box2D/Dynamics/Contacts/b2Contact.cpp>
#include <Box2D/Dynamics/Joints/b2Joint.cpp>
#include <Box2D/Dynamics/Joints/b2DistanceJoint.cpp>
#include <Box2D/Dynamics/Joints/b2FrictionJoint.cpp>
#include <Box2D/Dynamics/Joints/b2GearJoint.cpp>
#include <Box2D/Dynamics/Joints/b2MotorJoint.cpp>
#include <Box2D/Dynamics/Joints/b2MouseJoint.cpp>
#include <Box2D/Dynamics/Joints/b2PrismaticJoint.cpp>
#include <Box2D/Dynamics/Joints/b2PulleyJoint.cpp>
#include <Box2D/Dynamics/Joints/b2RevoluteJoint.cpp>
#include <Box2D/Dynamics/Joints/b2RopeJoint.cpp>
#include <Box2D/Dynamics/Joints/b2WeldJoint.cpp>
#include <Box2D/Dynamics/Joints/b2WheelJoint.cpp>
#include <Box2D/Particle/b2ParticleSystem.cpp>

#include "Common/b2Math.cpp"
#include "Dynamics/b2WorldJsBindings.cpp"
#include "Dynamics/b2BodyJsBindings.cpp"
